sudo: false
branches:
  only:
    - master
language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "4"
  - "5"
script:
  - npm run test:cov
after_success:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
